name: Build iOS app

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install @angular/cli
      run: npm i -D -E @angular/cli
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 9
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: Build
      run: |
          ionic cordova platform add ios
          ionic cordova build ios --prod
    - name: List
      run: ls -l platforms/ios
    - name: Analyze
      run: xcodebuild -project platforms/ios/MyApp.xcodeproj -scheme MyApp -sdk iphoneos clean analyze
    - name: Build ios app
      run: xcodebuild -scheme MyApp -workspace platforms/ios/MyApp.xcworkspace/ build
    - name: Upload app
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: platforms/ios
    
