name: Build Android app

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Fetch release version
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Install @angular/cli
      run: npm i -D -E @angular/cli
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 10
    - name: Build
      run: ionic cordova build android --prod --release
