name: Build iOS app

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install @angular/cli
      run: npm i -D -E @angular/cli
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 9
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.4.app
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: Build
      run: |
          ionic cordova platform add ios
          ionic cordova build ios --prod
    - name: List
      run: ls -l platforms/ios/build/emulator/
        
