name: Build iOS app

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Test
      run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
    - name: Install @angular/cli
      run: npm i -D -E @angular/cli
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 9
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: Build
      run: |
          ionic cordova platform add ios
          ionic cordova build ios --prod --release
    - name: List
      run: ls -l platforms/ios
    - name: Upload app
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: platforms/ios
    
